# Generated by Django 4.2.7 on 2024-01-30 11:56
from django.db import migrations, models
from django.utils.text import slugify

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, blank=True),
        ),
    ]

    def generate_slug(apps, schema_editor):
        Author = apps.get_model('catalog', 'Author')
        for author in Author.objects.all():
            author.slug = slugify(author.full_name)
            author.save()

    operations += [
        migrations.RunPython(generate_slug, migrations.RunPython.noop),
    ]

    # Optional: You can remove the original AutoSlugField
    operations += [
        migrations.RemoveField(
            model_name='author',
            name='slug',  # Replace with the actual name if different
        ),
    ]
